name: 📦 Install dependencies
description: 'Installs dependencies using pnpm.'
runs:
  using: 'composite'
  steps:
    - name: Get pnpm cache directory path
      id: pnpm-cache
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: 📦 Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
