name: Bot CI

on:
  pull_request:

env:
  SERVICE_NAME: 'bot'
  NODEJS_VERSION: '18.12.1'
  PNPM_VERSION: '7.30.1'

jobs:
  changes:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    outputs:
      bot: ${{ steps.filter.outputs.bot }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            bot:
              - 'bot/**'
              - '.github/workflows/bot.yml'

  bot-ci:
    needs: changes
    if: needs.changes.outputs.bot == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Install pnpm globally
        run: npm install -g pnpm

      - name: Install dependencies globally
        run: pnpm install --no-frozen-lockfile

      - name: Install dependencies on bot
        run: pnpm install --no-frozen-lockfile
        working-directory: ./bot

      - name: Restore Github Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-platform-server-${{ hashFiles('pnpm-lock.yaml', '**/pnpm-lock.yaml') }}

      - name: Run Linter
        run: pnpm lint
        working-directory: ./bot

      - name: Run Tests
        run: pnpm test
        working-directory: ./bot

      - name: Run Prettier Formatting
        run: npx prettier --write .

      - name: Run Build
        run: pnpm build
        working-directory: ./bot

  workflow:
    needs: [changes, bot-ci]
    if: always() && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Report final CI status
        run: |
          if [[ "${{ needs.changes.result }}" == "failure" || "${{ needs.bot-ci.result }}" == "failure" || "${{ needs.bot-ci.result }}" == "cancelled" ]]; then
            echo "Bot CI failed or was cancelled."
            exit 1
          fi
          echo "Bot CI passed or was not required for this PR."
